enum SalesOverviewPeriod {
    DAILY
    WEEKLY
    MONTHLY
    YEARLY
}

type Dashboard {
    totalSales: Float!
    totalProducts: Int!
    totalCustomers: Int!
    totalUnitsInStock: Int!

    getSalesOverview(period: SalesOverviewPeriod!): [SaleOverviewRow!]!
}