export const ErrorCode = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  BAD_USER_INPUT: "BAD_USER_INPUT",
  CONFLICT: "CONFLICT",
  ACCOUNT_RESTRICTED: "ACCOUNT_RESTRICTED",
} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];

