export * from './actions';
export * from './location';
export * from './customer-info';
export * from './phone';
export * from './email';
export * from './total-orders';
export * from './total-spent';
export * from './last-purchase';
export * from './customer-since';
